Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.hostname = "superset"

  config.vm.box_check_update = false

  config.vm.network "private_network", ip: "192.168.100.3"


  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = "superset"
    vb.cpus = 2
    vb.memory = "4096"
  end

  config.vm.provision "shell", inline: <<-SHELL
    yum update -y --quiet
    yum install -y wget tar nano net-tools lsof \
    gcc gcc-c++ libffi-devel python-devel python-pip\
    python-wheel openssl-devel cyrus-sasl-devel openldap-devel
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    pip install --upgrade setuptools pip
    pip install apache-superset
  SHELL
end
