Vagrant.configure("2") do |config|

  config.vm.box = "archlinux/archlinux"

  config.vm.hostname = "192.168.100.2"

  config.vm.box_check_update = false

  config.vm.network "private_network", ip: "192.168.100.2"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = "solr-server"
    vb.memory = "3072"
  end

  config.vm.provision "shell", inline: <<-SHELL
    pacman -Syu --noconfirm --needed
    pacman -Syu --noconfirm -needed wget curl tar nano net-tools 
    echo y | pacman -Syu jdk8-openjdk --noconfirm --needed
  SHELL
end
