Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.hostname = "solr-server"

  config.vm.box_check_update = false

  config.vm.network "private_network", ip: "192.168.100.2"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = "solr-server"
    vb.memory = "3072"
  end

  config.vm.provision "shell", inline: <<-SHELL
    yum update -y --quiet
    yum install -y wget tar nano net-tools lsof
    yum install -y java-1.8.0-openjdk
  SHELL

  # config.vm.provision "shell", path: "solr-install.sh"
end
